### ISSUE TITLE
测试成功过了吗？如何自动勾选保存网盘的内容？

### ISSUE THREAD

**Issue by yhzwy7228333** [VinylChloride/BaiduNetDiskAutoTransfer#1]
如何自动勾选保存网盘的内容，没有这个操作转存没有成功啊
代码里没有，对js没有大的了解不知道怎么写。

**Comment by VinylChloride** [comment]
已更新新版本，请参考更新日志，之前上传的是第一版，后续版本没有继续上传，学生党时间不多见谅
